# Generated by Django 2.2.6 on 2019-11-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('cast_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(null=True)),
                ('tmdb_name', models.CharField(max_length=100, null=True)),
                ('imdb_id', models.CharField(max_length=9, null=True)),
                ('imdb_name', models.CharField(max_length=100, null=True)),
                ('seasons', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('ep_num', models.IntegerField(null=True)),
                ('tmdb_id', models.IntegerField(null=True)),
                ('tmdb_name', models.CharField(max_length=100, null=True)),
                ('imdb_id', models.CharField(max_length=9, null=True)),
                ('imdb_name', models.CharField(max_length=100, null=True)),
                ('season', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvapi.Show')),
            ],
        ),
    ]
